### ISSUE TITLE
Commanding units can see all other units in GeoBroker

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#17]
The visibility matrix shall be updated in a way, that a commanding unit can see all their units.

Definition of commanding unit: Unit of type "Officer" (German "Führungskraft")

An Officer unit can see all units and incidents of the same concern, if the geobroker setting "geobroker.all.units.for.officers" is set to true.

**Comment by heinrichmartin** [comment]
Initially, all commanding units shall shall see all units and all incidents. This can be improved later. Also, if commanding units are not yet flagged, use the naming scheme for now.
