### ISSUE TITLE
set last position when unit is at home

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/CoCeSo#22]
geoclient does not show the gray vector from the last position when unit status is "at home"

**Comment by robo-w** [comment]
it was filtered too early in the geobroker plugin. Also there is a bug in the existing Coceso implementation, which leads to a lost position update. the update is published to the client, but not persisted in the database.
This change requires more investigation in the persistence component, and also changes with major impact to the overall stability of the system. This will *not* be fixed for this year.

@fs1 fyi
