### ISSUE TITLE
[Backend] Create SMS Sender Module

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#4]
The SMS Sender module can be registered in the Alarm Text Module (see #3).

The module is triggered by the Alarm Text Module with following information:
* Ids of targets (Phone numbers)
* Message content

The text message content is truncated to fit into a single text message.
The text message is sent to the targets via an external SMS Gateway.

The endpoint of the external SMS gateway is configurable.
Evaluate if [SMS Gateway](https://github.com/vvanholl/smsgateway-gammu) is usable. If not, a similar REST interface should abstract the physical SMS Sender.

Outcome of SMS Gateway evaluation: It is easy to setup, but sadly not thread safe. When multiple SMS are sent, some are lost or sent to wrong destinations.

A gammu head for sending SMS similar to SDS is available here: https://github.com/robo-w/java-gammu-head

**Comment by kopfi** [comment]
In Kufstein, we already use CoCeSo with a Quick-n-Dirty SMS sending solution.
As I have a little bit more spare time this summer, I would like to take care of the "outgoing sms support" milestone.

May I be free to adapt the story a little bit to my needs? (E.g. implement it with a A1-Service beforehand and add other solutions later)

**Comment by robo-w** [comment]
@kopfi is there any code we could re-use in the trunk of the repository? I plan to change the standalone alarm-manager solution to an integrated one in CoCeSo. The SMS sender and SDS sender are both ready, so I would next tackle the CoCeSo implementation.

**Comment by robo-w** [comment]
Is now implemented, compatible to the Java Gammu Head API.
