### ISSUE TITLE
[UI] "Neuer Vorfall" dialogue doesn't focus in BO field

### ISSUE THREAD

**Issue by schwindp** [wrk-fmd/CoCeSo#73]
When opening a new Vorfall using the space key, input isn't automatically focussed in BO field, so you always need to use the mouse or an additional TAB key.

Expected behaviour: Automatically set the input focus in the BO field after opening a new Vorfall.

**Comment by robo-w** [comment]
The autofocues tag is set on the BO field, and apparently it is only an issue, if it is opened by the keyboard shortcut.
@danielsteiner: Can you have a look, why it behaves differently on opening via click and keyboard?

**Comment by robo-w** [comment]
Fixed by knockout JS "hasFocus: true" in data-bind field. It works in most cases, only if a context menu of an incident is opened while the spacebar is pressed, the focus still does not work. I think we can live with this :)
