### ISSUE TITLE
inconsistent documentation of deployment

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/CoCeSo#8]
`Readme.md` differs from `main/resources/INSTALL.txt`. Which one is accurate? Suggesting to maintain the correct content and drop the other file from the repo.

**Comment by robo-w** [comment]
in the INSTALL.txt the geocode initialization script is missing. From the basic steps it is the same, but phrased differently.

For the installation the readme should be used, is suggest to drop the install.txt
