### ISSUE TITLE
[UI] Make "OK" button always clickable

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#89]
The "OK" button should be always clickable, even if there are no changes to save. If there are no unsaved changes, the OK button shall only close the edit window.

**Comment by heinrichmartin** [comment]
As a general remark about UI design, I like seeing whether anything changed or not - given that a Cancel/Close button is always available. Ideally, the Cancel button is the default action (acts on return key) iff OK is disabled. Alternatively, another UI element indicates changes.

**Comment by robo-w** [comment]
Right now we have in Coceso "OK", "Save", "Reset". "OK" saves and closes the window, "Save" saves the changes and keeps it open, and "Reset" reverts all local changes.
I see two options here:
* Make the OK button always clickable
* Change the "Reset" button to a "Cancel" button, which can be always clicked

I don't know if the reset feature was ever used, maybe we should evaluate this at one of the next events.
