### ISSUE TITLE
Autosuggest Units based on required type and location

### ISSUE THREAD

**Issue by danielsteiner** [wrk-fmd/CoCeSo#95]
In stressfull situations, it can be, that the person who decides which unit has to be asigned (dispatcher or tactic officer) misses a unit that would be nearer to the incident location. To prevent this, the current location of all units should be sent back to CoCeSo from the geobroker and then recomended if the incident type is either priorized or if "special signal" is set to true. 
This could be realised with a view similar to lstsim.de (see attached screenshot) 
Also, units should be able to be filtered by type. 
Additionally, a Quickselect button should be implemented to automatically select the nearest unit matching the selected type. 

![lstsim](https://user-images.githubusercontent.com/1122125/55724813-804abd80-5a0c-11e9-80bc-982920890bce.PNG)

**Comment by robo-w** [comment]
this needs a bigger design session of multiple parts. Since the github tracker will be no longer used for those tickets, moved to Jira.
